### PR TITLE
Bevy 0.6

### PR DESCRIPTION
**Pull request by johanhelsing**
Not sure if this is any help, but I started trying to get this to run with bevy 0.6.

I started off of the `bevy-main` branch, and got it to a state where it compiles, but some features are disabled (transform-gizmo).

And picking also seems to be broken.

I commented out the `currently_inspected_system` because I was a little bit too tired to figure out how to properly fix it.

### CODE REVIEW

**Comment by jakobhellermann** [comment]
Thanks for the PR.

I've been reworking the UI of a potential in-app bevy editor a bit from scratch so since you seem to be using `bevy_editor_pls`, which features of it do you actually care about?

So far in my from-scratch redesign I have arbitrary editor windows as panels working, with a built-in hierarchy and inspector window:
image
And a half-baked editor camera.

Once there is a proper editor camera, is there anything else you would be missing coming from the current state of things?

**Comment by johanhelsing** [comment]
Cool!

> I've been reworking the UI of a potential in-app bevy editor a bit from scratch so since you seem to be using `bevy_editor_pls`, which features of it do you actually care about?

Picking + inspector is the main thing, and having some sort of controllable camera. I've only been using it for 2d.

I'm working on [a tutorial about making a physics engine](https://johanhelsing.studio/posts/physics-06-debugging) and it's a nice way to add inspection of items that doesn't require too much of an explanation.

**Comment by johanhelsing** [comment]
Gave it a whirl!

Looks really useful!

image

Some notes, though I guess many of these are probably already on your todo list.

1. ctrl+picking outside editor doesn't work for me (I did add EditorRayCastSource to my camera, but maybe it's because it's orthographic? When the overlay is enabled, it works.
2. camera controls are weird. I seem to be able to pan with the right mouse button, but it's the reverse of what you'd expect
3. Frame time needs more decimals.
4. It's sort of confusing that play/pause icons toggle the overlay.
5. Maybe double clicking an entity in the hierarchy could open the inspector window (if not already open)

Docks are cool! I also like that it's easy to toggle between a full and more minimal type of editor.

**Comment by jakobhellermann** [comment]
Github closed this automatically because I renamed the `main` branch to `old-main`. I'll work on the new version now, if you miss anything that was possible previously please open an issue and I'll work on getting it back :slightly_smiling_face:

**Pull request closed without merging**
