### PR TITLE
Merge main into bevy-main and fix compile errors

### PR DESCRIPTION
**Pull request by johanhelsing**
I have two pending PRs in bevy_mod_picking and jakobhellermann/bevy_fly_camera/bevy-main that should go in first

### CODE REVIEW

**Comment by johanhelsing** [comment]
https://github.com/aevyrie/bevy_mod_picking/pull/104
https://github.com/jakobhellermann/bevy_fly_camera/pull/1

**Comment by johanhelsing** [comment]
Ok, so I got it to compile, but it panicks when I try to use it in my project:

```
Sep 21 20:34:43.241  WARN bevy_ecs::schedule::graph_utils: bevy_transform_gizmo::picking::disable_mesh_picking_during_gizmo_hover wants to be before unknown label: Focus
Sep 21 20:34:43.241  WARN bevy_ecs::schedule::graph_utils: bevy_transform_gizmo::grab_gizmo wants to be after unknown label: Focus
Sep 21 20:34:43.241  WARN bevy_ecs::schedule::graph_utils: bevy_transform_gizmo::grab_gizmo wants to be before unknown label: Selection
thread 'Compute Task Pool (11)' panicked at 'Resource requested by bevy_transform_gizmo::picking::disable_mesh_picking_during_gizmo_hover does not exist: bevy_mod_picking::PickingPluginState', C:\Users\Johan\dev\bevy\crates\bevy_ecs\src\system\system_param.rs:436:17
```

Haven't had time to test with the examples yet

**Comment by johanhelsing** [comment]
Ok, it happens with the examples as well.

It's due to a duplicate dependency on bevy_mod_picking. Guess we should either patch it or use the same one as  bevy_transform_gizmo bevy-main uses

**Comment by jakobhellermann** [comment]
You can try running `cargo tree -i bevy_mod_picking`, that should print the versions used.

**Comment by johanhelsing** [comment]
Got it working :)

Ok, so it seems that aevyrie hasn't been responding to PRs on bevy_mod_picking since august... Not really sure what the best way to solve this is... We could:

1. Use the same fork as bevy_transform_gizmo bevy-main uses (https://github.com/JulianRuiseco/bevy_mod_picking), which also depends on JulianRuiseco's a fork of bevy_mod_raycast
2. Use my version of bevy_mod_picking with unchanged version of bevy_mod_raycast
3. Make a fork on your account (same way you do with jakobhellermann/bevy_fly_cam)

**Comment by jakobhellermann** [comment]
I'm fine with with 2. GitHib says ther are remaining conflicts, once you fix them I'll merge 👍

**Comment by johanhelsing** [comment]
Ok, should be ready now :)

**Comment by johanhelsing** [comment]
Ok, I'll have to sort of the conflicts later

**Comment by jakobhellermann** [comment]
I just had some trouble with git, but I think I fixed it and pushed your code to `bevy-main` directly. Can you make sure that it works?

**Comment by jakobhellermann** [comment]
If it works we can just close this PR since the code is now in `bevy-main` anyways

**Comment by johanhelsing** [comment]
So I need to copy the two patches to my project as well

```
[patch."https://github.com/aevyrie/bevy_mod_picking"]
bevy_mod_picking = { git = "https://github.com/johanhelsing/bevy_mod_picking", branch = "update-to-latest-bevy" }
[patch."https://github.com/JulianRuiseco/bevy_mod_picking"]
bevy_mod_picking = { git = "https://github.com/johanhelsing/bevy_mod_picking", branch = "update-to-latest-bevy" }
```

But then it works. I guess if we'd want to fix that, we'd need to fork bevy_transform_gizmo bevy-main to use a different bevy_mod_picking

I'm ok with patching for now

**Comment by jakobhellermann** [comment]
Yep, that is because patches only apply for the current crate, not for dependencies.
Thanks for the PR, i guess I can close this now that it's merged unconventionally :smile:

**Pull request closed without merging**
